using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
   private Rigidbody playerRb;
   public float speed = 5.0f;
   private GameObject focalpoint;
    // Start is called before the first frame update
    void Start()
    {
        playerRb = GetComponent<Rigidbody>();
        focalpoint = GameObject.Find("Focal Point");
    }

    // Update is called once per frame
    void Update()
    {
      float forwardInput = Input.GetAxis("Vertical");
     playerRb.AddForce(focalpoint.transform.forward * forwardInput * speed);
    }

}
